---
# SMTP configuration, depends on VM host or SMTP credentials
EDXAPP_EMAIL_HOST: "%%EDXAPP_EMAIL_HOST%%"
#EDXAPP_EMAIL_HOST_USER: "%%EDXAPP_EMAIL_HOST_USER%%"
#EDXAPP_EMAIL_HOST_PASSWORD: "%%EDXAPP_EMAIL_HOST_PASSWORD%%"
#EDXAPP_EMAIL_PORT: %%EDXAPP_EMAIL_PORT%%
#EDXAPP_EMAIL_USE_TLS: %%EDXAPP_EMAIL_USE_TLS%%

# Database connections - need to confirm connection strings
ORA_MYSQL_HOST: "%%CLUSTERNAME%%mysql1"
XQUEUE_MYSQL_HOST: "%%CLUSTERNAME%%mysql1"
EDXAPP_MYSQL_HOST: "%%CLUSTERNAME%%mysql1"
EDXAPP_MEMCACHE: ["%%CLUSTERNAME%%mysql1:11211"]
MONGO_BIND_IP: "0.0.0.0"
FORUM_MONGO_HOSTS: ["%%CLUSTERNAME%%rs1/%%CLUSTERNAME%%mongo1,%%CLUSTERNAME%%mongo2,%%CLUSTERNAME%%mongo3"]
EDXAPP_MONGO_HOSTS: ["%%CLUSTERNAME%%rs1/%%CLUSTERNAME%%mongo1,%%CLUSTERNAME%%mongo2,%%CLUSTERNAME%%mongo3"]
