#!/bin/bash
# Copyright (c) Microsoft Corporation. All Rights Reserved.
# Licensed under the MIT license. See LICENSE file on the project webpage for details.
# Note, this is generated by manually grabbing values from stamp.json.
#   todo: generate this file dynamically so that changes in stamp.json will be reflected automatically
#   todo: mask secrets by relying on "replace" transform

#todo:
#set -x

cd ..

mongoDbInstallerScript=mongodb-ubuntu-install.sh
mongoMachineSettings_installerBaseUrl=http:\/\/repo.mongodb.org\/apt\/ubuntu
mongoMachineSettings_installerPackages=mongodb-org
networkSettings_serverIpPrefix=10.0.0.
networkSettings_mongoDataNodeCount=1

# configurable, but hardcoded for now
mongoReplicaSetName=clustername-rs1
mongoServerAdminUserName=stepdo
mongoServerAdminPassword=hokie

# generally randomly generated, but hardcoded for now
mongoReplicaSetKey=tcvhiyu5h2o5o

bash $mongoDbInstallerScript -i $mongoMachineSettings_installerBaseUrl -b $mongoMachineSettings_installerPackages -r $mongoReplicaSetName -k $mongoReplicaSetKey -u $mongoServerAdminUserName -p $mongoServerAdminPassword -x $networkSettings_serverIpPrefix -n $networkSettings_mongoDataNodeCount
