# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: |
          docker pull solita/ubuntu-systemd:16.04
          docker run --rm --privileged -v /:/host solita/ubuntu-systemd:16.04 setup

          # Host entries from edx-configuration/playbooks/roles/local_dev/tasks/main.yml
          # "priveleged" to support THP changes in edx-configuration/playbooks/roles/mongo_3_2/tasks/main.yml
          docker run -d --name stepdo0 --add-host "localhost preview.localhost":127.0.0.1 --privileged --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t solita/ubuntu-systemd:16.04

          # List all containers
          docker ps -a

          # Prepare cgroup on the host at /tmp/cgroup to avoid error: "failed to connect to bus: no such file or directory"
          sudo mkdir -p /tmp/cgroup/systemd && sudo mount -t cgroup systemd /tmp/cgroup/systemd -o ro,noexec,nosuid,nodev,none,name=systemd

      # run tests!
      - run:
          name: run tests
          command: source ./tests/deploy-onebox.sh