---
# SMTP configuration, depends on VM host or SMTP credentials
EDXAPP_EMAIL_HOST: "openedx-mysql"

# Database connections
ORA_MYSQL_HOST: "openedx-mysql"
XQUEUE_MYSQL_HOST: "openedx-mysql"
EDXAPP_MYSQL_HOST: "openedx-mysql"
EDXAPP_MEMCACHE: ["openedx-mysql:11211"]
MONGO_BIND_IP: "0.0.0.0"
FORUM_MONGO_HOSTS: ["openedx-mongo"]
EDXAPP_MONGO_HOSTS: ["openedx-mongo"]

EDXAPP_LMS_SITE_NAME: "%%CLUSTERNAME%%lms.%%REGION%%.cloudapp.azure.com"
EDXAPP_CMS_SITE_NAME: "%%CLUSTERNAME%%cms.%%REGION%%.cloudapp.azure.com"
EDXAPP_LMS_BASE: "{{ EDXAPP_LMS_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}:18010"
EDXAPP_PREVIEW_LMS_BASE: "{{ EDXAPP_LMS_BASE }}"

# EDXAPP_SITE_NAME is used in many places like:
#   Activation link
#   Password reset link
#   Course live view link
EDXAPP_SITE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}"

EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443

EDXAPP_LMS_PREVIEW_NGINX_PORT: 18020
EDXAPP_CMS_NGINX_PORT: 18010
EDXAPP_CMS_SSL_NGINX_PORT: 48010

NGINX_ENABLE_SSL: %%NGINX_ENABLE_SSL%%
NGINX_REDIRECT_TO_HTTPS: %%NGINX_ENABLE_SSL%%
NGINX_SSL_CERTIFICATE: %%NGINX_SSL_CERTIFICATE%%
NGINX_SSL_KEY: %%NGINX_SSL_KEY%%
