---
# Modifying Language list. null means language is removed from the list. Others either language is a new added language or display name is changed.
EDXAPP_ALL_LANGUAGES_OVERRIDE:
  AE: null,
  AFB: "Arabic, Gulf",
  AGQ: "Aghem",
  AN: null,
  APC: "Arabic, Levantine",
  ARN: "Mapudungun",
  ARZ: "Arabic, Egyptian",
  ASA: "Asu",
  AST: "Asturian",
  AV: null,
  AY: null,
  AZ-CYRL: "Azerbaijani (Cyrillic)",
  AZ-LATN: "Azerbaijani (Latin)",
  BAS: "Basaa",
  BEM: "Bemba",
  BEZ: "Bena",
  BH: null,
  BI: null,
  BIN: "Edo",
  BM: null,
  BM-LATN: "Bamanankan (Latin)",
  BN: "Bangla",
  BO: "Tibetan",
  BRX: "Bodo",
  BS-CYRL: "Bosnian (Cyrillic)",
  BS-LATN: "Bosnian (Latin)",
  BYN: "Blin",
  CA-ES-VALENCIA: "Valencian",
  CEB: "Cebuano",
  CGG: "Chiga",
  CH: null,
  CHR-CHER: "Cherokee (Cherokee)",
  CR: null,
  CS: "Czech",
  CV: null,
  CY: "Welsh",
  DA: "Danish",
  DAV: "Taita",
  DE: "German",
  DGO: "Dogri",
  DJE: "Zarma",
  DSB: "Lower Sorbian",
  DUA: "Duala",
  DV: "Divehi",
  DYO: "Jola-Fonyi",
  EBU: "Embu",
  EL: "Greek",
  ES: "Spanish",
  EWO: "Ewondo",
  FA: "Persian",
  FF-LATN: "Fulah",
  FI: "Finnish",
  FIL: "Filipino",
  FJ: "Fijian",
  FO: "Faroese",
  FR: "French",
  FUR: "Friulian",
  FY: "Western Frisian",
  GA: "Irish",
  GD: "Scottish Gaelic",
  GL: "Galician",
  GN: "Guarani",
  GSW: "Swiss German",
  GU: "Gujarati",
  GUZ: "Gusii",
  GV: "Manx",
  HA-LATN: "Hausa (Latin)",
  HAW: "Hawaiian",
  HE: "Hebrew",
  HI: "Hindi",
  HO: null,
  HSB: "Upper Sorbian",
  HU: "Hungarian",
  HZ: null,
  IE: null,
  IG: "Igbo",
  II: "Yi",
  IK: null,
  IO: null,
  IS: "Icelandic",
  IT: "Italian",
  IU-CANS: "Inuktitut (Canadian Aboriginal Syllabics)",
  IU-LATN: "Inuktitut (Latin)",
  IV: "Invariant Language",
  JA: "Japanese",
  IGO: "Ngomba",
  JMC: "Machame",
  JV: null,
  JV-LATN: "Javanese (Latin)",
  KA: "Georgian",
  KAB: "Kabyle",
  KAM: "Kamba",
  KDE: "Makonde",
  KEA: "Kabuverdianu",
  KFR: "Kutchi",
  KG: null,
  KHQ: "Koyra Chiini",
  KI: "Kikuyu",
  KJ: null,
  KK: "Kazakh",
  KKJ: "Kako",
  KL: "Greenlandic",
  KLN: "Kalenjin",
  KM: "Khmer",
  KMR-ARAB: "Northern Kurdish (Arabic)",
  KO: "Korean",
  KOK: "Konkani",
  KS: null,
  KS-ARAB: "Kashmiri (Perso-Arabic)",
  KSB: "Shambala",
  KS-DEVA: "Kashmiri (Devanagari)",
  KSF: "Bafia",
  KSH: "Colognian",
  KU-ARAB: "Central Kurdish",
  KV: null,
  KY: "Kyrgyz",
  LA: null,
  LAG: "Langi",
  LB: "Luxembourgish",
  LG: "Ganda",
  LI: null,
  LKT: "Lakota",
  LRC: "Northern Luri",
  LU: "Luba-Katanga",
  LUO: "Luo",
  LUY: "Luyia",
  MAI: "Maithili",
  MAS: "Masai",
  MER: "Meru",
  MFE: "Morisyen",
  MG: "Malagasy",
  MGH: "Makhuwa-Meetto",
  MGO: "Meta'",
  MH: null,
  MI: "Maori",
  MK: "Macedonian",
  MN: null,
  MN-CYRL: "Mongolian (Cyrillic)",
  MNI: "Manipuri",
  MN-MONG: "Mongolian (Traditional Mongolian)",
  MOH: "Mohawk",
  MR: "Marathi",
  MS: "Malay (Latin)",
  MUA: "Mundang",
  MWW: "Hmong Daw",
  MZN: "Mazanderani",
  NA: null,
  NAQ: "Nama",
  NB: "Norwegian Bokmål",
  ND: "North Ndebele",
  NDS: "Low German",
  NG: null,
  NMG: "Kwasio",
  NN: "Norwegian Nynorsk",
  NNH: "Ngiemboon",
  NO: null,
  NGO: "N’Ko",
  NR: "South Ndebele",
  NSO: "Sesotho sa Leboa",
  NUS: "Nuer",
  NV: null,
  NY: null,
  NYN: "Nyankole",
  OJ: null,
  OM: "Oromo",
  OR: "Odia",
  OS: null,
  OS-CYRL: "Ossetic (Cyrillic)",
  OTQ: "Querétaro Otomi",
  PA: null,
  PA-ARAB: "Punjabi (Arabic)",
  PA-GURU: "Punjabi (Gurmukhi)",
  PAP: "Papiamento",
  PI: null,
  PL: "Polish",
  PRG: "Prussian",
  PRS: "Dari",
  PS: "Pashto",
  PT: "Portuguese",
  PT-BR: "Portuguese (Brazil)",
  PT-PT: "Portuguese (Portugal)",
  QPS: "Pseudo",
  QUC: "K’iche’",
  RM: "Romansh",
  RN: "Rundi",
  RO: "Romanian",
  ROF: "Rombo",
  RU: "Russian",
  RW: "Kinyarwanda",
  RWK: "Rwa",
  SA: "Sanskrit",
  SAH: "Sakha",
  SAQ: "Samburu",
  SAT-DEVA: "Santali (Devanagari)",
  SPB: "Sangu",
  SC: null,
  SD: null,
  SD-ARAB: "Sindhi (Arabic)",
  SD-DEVA: "Sindhi (Devanagari)",
  SE: "Northern Sami",
  SEH: "Sena",
  SES: "Koyraboro Senni",
  SG: "Sango",
  SHI-LATN: "Tachelhit (Latin)",
  SHI-TFNG: "Tachelhit (Tifinagh)",
  SI: "Sinhala",
  SK: "Slovak",
  SM: "Samoan",
  SMA: "Southern Sami",
  SMJ: "Lule Sami",
  SMN: "Inari Sami",
  SMS: "Skolt Sami",
  SO: "Somali",
  SR: null,
  SR-CYRL: "Serbian (Cyrillic)",
  SR-LATN: "Serbian (Latin)",
  SS: "siSwati",
  SSY: "Saho",
  ST: "Sesotho",
  SV: "Swedish",
  SW: "Kiswahili",
  SWC: "Congo Swahili",
  SYR: "Syriac",
  TE: "Telugu",
  TEO: "Teso",
  TG: null,
  TG-CYRL: "Tajik (Cyrillic)",
  TH: "Thai",
  TI: "Tigrinya",
  TIG: "Tigre",
  TK: null,
  TK-LATIN: "Turkmen (Latin)",
  TL: null,
  TN: "Setswana",
  TO: "Tongan",
  TR: "Turkish",
  TS: "Xitsonga",
  TT: null,
  TT-CYRL: "Tatar (Cyrillic)",
  TW: null,
  TWQ: "Tasawaq",
  TY: "Tahitian",
  TZM-ARAB: "Central Atlas Tamazight (Arabic)",
  TZM-LATN": "Central Atlas Tamazight (Latin)",
  TZM-TFNG: "Central Atlas Tamazight (Tifinagh)",
  UG: null,
  UG-ARAB: "Uyghur (Arabic)",
  UK: "Ukrainian",
  UZ: null,
  UZ-ARAB: "Uzbek (Perso-Arabic)",
  UZ-CYRL: "Uzbek (Cyrillic)",
  UZ-LATN: "Uzbek (Latin)",
  VAI-LATN: "Vai (Latin)",
  VAI-VAII: "Vai (Vai)",
  VE: "Venda",
  VI: "Vietnamese",
  VO: "Volapük",
  VUN: "Vunjo",
  WA: null,
  WAE: "Walser",
  WAL: "Wolaytta",
  WO: "Wolof",
  XH: "isiXhosa",
  XOG: "Soga",
  YAV: "Yangben",
  YUA: "Yucatec Maya",
  YUE-HANT: "Cantonese (Traditional)",
  ZA: null,
  ZGH-TFNG: "Standard Moroccan Tamazight (Tifinagh)",
  ZH: null,
  ZH-HANS: "Chinese (Simplified)",
  ZH-HANT: "Chinese (Traditional)",
  ZU: "isiZulu"

