---
- name: Apply theming compile assets workaround
  sudo: yes
  shell: bash ./update_theme.sh "{{ theme_branch }}" "{{ theme_repo }}" "{{ EDXAPP_THEME_ENVIRONMENT }}" "{{ EDXAPP_COMPREHENSIVE_THEME_DIRS }}" "{{ oxa_tools_path }}" "{{ secrets_path }}" "{{ edx_platform_path }}"
  args:
    chdir: "{{ edxapp_files_path }}"
  register: bash_theme
  when: "{{ EDXAPP_ENABLE_COMPREHENSIVE_THEMING }}"

  # Print the shell tasks's stdout and stderr.
- debug: var="bash_theme.stdout_lines + [ bash_theme.stderr ]"
