---

##########################
# MYSQL
##########################

- name: Remove a cron job for mysql-backup
  sudo: yes
  cron:
    name="Remove MySQL backup job"
    cron_file=mysql_backup
    state=absent

# Print the shell tasks's stdout and stderr.
- debug: var="bash_theme.stdout_lines + [ bash_theme.stderr ]"

- name: Schedule MySQL backups
  sudo: yes
  cron:
    name="Create MySQL backup job"
    user="{{ os_admin_username }}"
    cron_file=mysql_backup
    minute=5 #TODO hour=23
    #TODO verify working dirrection is correct and bash/sudo aren't needed.
    job="cd {{ oxa_tools_path }} && {{ jumpbox_files_path }}/mysql_db_backup.sh --environment-file {{ env_file }}"

# Print the shell tasks's stdout and stderr.
- debug: var="bash_theme.stdout_lines + [ bash_theme.stderr ]"

##########################
# MONGO
##########################

- name: Remove a cron job for mongo-backup
  sudo: yes
  cron:
    name="Remove Mongo backup job"
    cron_file=mongo_backup
    state=absent

# Print the shell tasks's stdout and stderr.
- debug: var="bash_theme.stdout_lines + [ bash_theme.stderr ]"

- name: Schedule Mongo backups
  sudo: yes
  cron:
    name="Create Mongo backup job"
    user="{{ os_admin_username }}"
    cron_file=mongo_backup
    minute=5 #TODO hour=23
    #TODO verify working dirrection is correct and bash/sudo aren't needed.
    job="cd {{ oxa_tools_path }} && {{ jumpbox_files_path }}/mongo_db_backup.sh --environment-file {{ env_file }}""

# Print the shell tasks's stdout and stderr.
- debug: var="bash_theme.stdout_lines + [ bash_theme.stderr ]"
