edx_platform_repo: "%%PLATFORM_REPO%%"
edx_platform_version: "%%PLATFORM_VERSION%%"
edx_ansible_source_repo: "%%CONFIGURATION_REPO%%"
configuration_version: "%%CONFIGURATION_VERSION%%"
certs_version: "%%EDX_VERSION%%"
forum_version: "%%FORUM_VERSION%%"
xqueue_version: "%%EDX_VERSION%%"
demo_version: "%%EDX_VERSION%%"
ECOMMERCE_VERSION: "%%EDX_VERSION%%"
ECOMMERCE_WORKER_VERSION: "%%EDX_VERSION%%"
PROGRAMS_VERSION: "%%EDX_VERSION%%"

EDXAPP_PLATFORM_NAME: "%%PLATFORM_NAME%%"
EDXAPP_LMS_SITE_NAME: "%%LMS_URL%%"
EDXAPP_CMS_SITE_NAME: "%%CMS_URL%%"
EDXAPP_PREVIEW_SITE_NAME: "%%PREVIEW_URL%%"
EDXAPP_SITE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}"
EDXAPP_LMS_BASE: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_SITE_NAME }}:18010"
EDXAPP_PREVIEW_LMS_BASE: "{{ EDXAPP_LMS_BASE }}"
EDXAPP_PYTHON_SANDBOX: false

# see: http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/feature_flags/feature_flag_index.html
EDXAPP_FEATURES:  
  ENABLE_THIRD_PARTY_AUTH: %%EDXAPP_ENABLE_THIRD_PARTY_AUTH%%
  ENABLE_OAUTH2_PROVIDER: %%EDXAPP_ENABLE_OAUTH2_PROVIDER%%
  ENABLE_SYSADMIN_DASHBOARD: true
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: false
  # PREVIEW_LMS_BASE must be localhost for course discovery to work with dns (openedx.slack - 9/14/16 @3:08pm)
  PREVIEW_LMS_BASE: "{{ EDXAPP_PREVIEW_SITE_NAME }}"
  DISABLE_COURSE_CREATION: true
  DISABLE_LIBRARY_CREATION: true
  ALLOW_ALL_ADVANCED_COMPONENTS: true
  ALLOW_HIDING_DISCUSSION_TAB: true
  CERTIFICATES_ENABLED: true
  CERTIFICATES_HTML_VIEW: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_VIDEO_UPLOAD_PIPELINE: true
  ENABLE_MOBILE_REST_API: %%EDXAPP_ENABLE_MOBILE_REST_API%%
  OAUTH_ENFORCE_SECURE: %%OAUTH_ENFORCE_SECURE%%
  # ENABLE_CSMH_EXTENDED: true 

# Comprehensive Theming Configuration
EDXAPP_COMPREHENSIVE_THEME_DIRS: %%EDXAPP_COMPREHENSIVE_THEME_DIRS%%
EDXAPP_ENABLE_COMPREHENSIVE_THEMING: %%EDXAPP_ENABLE_COMPREHENSIVE_THEMING%%
EDXAPP_DEFAULT_SITE_THEME: "%%EDXAPP_DEFAULT_SITE_THEME%%"
EDXAPP_THEME_ENVIRONMENT: "%%ENVIRONMENT%%"
COMPREHENSIVE_THEME_DIRS: "{{ EDXAPP_COMPREHENSIVE_THEME_DIRS }}"
