edx_platform_repo: "%%PLATFORM_REPO%%"
edx_platform_version: "%%PLATFORM_VERSION%%"
edx_ansible_source_repo: "%%CONFIGURATION_REPO%%"
configuration_version: "%%CONFIGURATION_VERSION%%"
certs_version: "%%EDX_VERSION%%"
forum_version: "%%FORUM_VERSION%%"
xqueue_version: "%%EDX_VERSION%%"
demo_version: "%%EDX_VERSION%%"
ECOMMERCE_VERSION: "%%EDX_VERSION%%"
ECOMMERCE_WORKER_VERSION: "%%EDX_VERSION%%"
PROGRAMS_VERSION: "%%EDX_VERSION%%"

COMMON_SSH_PASSWORD_AUTH: "yes"

EDXAPP_PLATFORM_NAME: "%%PLATFORM_NAME%%"
EDXAPP_LMS_SITE_NAME: "%%LMS_URL%%"
EDXAPP_CMS_SITE_NAME: "%%CMS_URL%%"
EDXAPP_SITE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}"
EDXAPP_LMS_BASE: "{{ EDXAPP_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_SITE_NAME }}:18010"
EDXAPP_PREVIEW_LMS_BASE: "{{ EDXAPP_LMS_BASE }}"
EDXAPP_PYTHON_SANDBOX: false

SEARCH_ENGINE: "search.elastic.ElasticSearchEngine"

EDXAPP_FEATURES:
  ENABLE_SYSADMIN_DASHBOARD: true
  PREVIEW_LMS_BASE: "{{ EDXAPP_PREVIEW_LMS_BASE }}"
  DISABLE_COURSE_CREATION: false
  ALLOW_ALL_ADVANCED_COMPONENTS: true
  ENABLE_COURSEWARE_SEARCH: true
  ENABLE_DASHBOARD_SEARCH: true
  ENABLE_COURSE_DISCOVERY: true
  ENABLE_COURSEWARE_INDEX: true
  ENABLE_LIBRARY_INDEX: true
