---
- name: Apply Microsoft Stanford Theming
  sudo: yes
  shell: bash ./update_theme.sh
  args:
    chdir: "{{ edxapp_files_path }}"
  register: bash

# Print the shell task's stdout and stderr.
- debug: var="bash.stdout_lines + [ bash.stderr ]"

